# Permalinks
permalink:        /:year/:month/:title/
#relative_permalinks: true

# Local
highlighter:      rouge
encoding:         utf-8
gems:             [jekyll-paginate]

# Dependencies
markdown:         kramdown
toc_levels:       2..3

# Setup
title:            '超哥B'
tagline:          '自由的邮递员'
description:      '自由的邮递员'
url:              http://chaogeb.com

author:
  name:           '超哥B'
  email:          procg@outlook.com
  url:            http://chaogeb.com

paginate:         8

# Custom vars

github:
  repo:           https://github.com/chaogeb
